---

- name: Enable nginx service
  hosts: web_server
  become: yes
  become_user: root
  
  tasks:
    - name: Install Nginx
      apt:
        name: nginx-extras
        update_cache: yes

    - name: Copy the nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/nginx.conf
        mode: '0644'

    - name: Copy the index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'
      notify: restart nginx

    - name: Start nginx service
      systemd:
        name: nginx
        state: started

  handlers:
    - include: handlers.yml
