---

- name: Add repository postgresql key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"

- name: Install postgresql
  apt:
    name:
      - "postgresql-{{ pg_version }}"
      - "postgresql-client-{{ pg_version }}"
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy postgresql configuration file
  template:
     src: postgresql.conf.j2
     dest: "/etc/postgresql/{{ pg_version }}/postgresql.conf"
     owner: postgres
     mode: 0644

- name: Connect to database
  postgresql_user:
    user: "{{ pg_user }}"
    password: "{{ pg_pass }}"
    encrypted: yes
  become: true
  become_user: "{{ pg_user }}"
  notify:  restart postgres
